# -*- coding: utf-8 -*-
"""编程语言类模块知识库。"""

KB_LANG = {}

KB_LANG["python"] = {
    "label": "Python",
    "related_title_hint": "数据类型、函数、模块、异常、并发",
    "axes": [
        "例如能够说出 Python 的动态类型、缩进语法与解释执行等基本特征。",
        "例如能够解释解释器与编译器的差异，以及 GIL 对并发的影响。",
        "例如能够编写函数、类与标准库调用的完整脚本。",
        "例如能够比较 Python 与 Java、Go 在类型系统与并发模型上的差异。",
        "例如能够评估不同实现方案（脚本、服务、库）的适用场景。",
        "例如能够组合标准库与第三方包设计完整的自动化工具。",
    ],
    "history": [
        "Python 由 Guido van Rossum 于 1991 年首次发布，设计哲学强调代码可读性与开发效率，核心思想记录在《Python 之禅》（PEP 20）中：优美优于丑陋、明确优于隐晦、简单优于复杂。",
        "Python 2 与 Python 3 的分裂期（2008-2020）是语言史上最重要的兼容性事件：Python 3 修复了字符串编码、整数除法等长期问题，但破坏性变更导致迁移缓慢；2020 年 1 月 Python 2 停止官方维护，社区全面转向 Python 3。",
        "Python 3.9 至 3.13 的演进带来了类型提示增强（PEP 604 的 X | Y 语法、PEP 695 的泛型语法）、性能优化（3.11 的 faster-calls 与自适应解释器）以及异步生态的成熟（asyncio、FastAPI、httpx）。",
        "Python 的应用版图从脚本自动化扩展到 Web 后端（Django、FastAPI）、数据科学（NumPy、Pandas、Matplotlib）、机器学习（PyTorch、scikit-learn）、运维自动化（Ansible）与科学计算，是当今最通用的编程语言之一。",
    ],
    "history_tail": [
        "对于初学者，理解 Python 的“电池内置”（标准库丰富）与“胶水语言”（易于调用 C/C++/Rust 扩展）两大特性，是判断其适用场景的基础。",
    ],
    "definitions": [
        "变量与动态类型：Python 变量是对象的引用，类型属于对象而非变量；`isinstance()` 与 `type()` 用于运行时检查，类型注解（PEP 484）提供静态检查能力但不改变运行时行为。",
        "缩进即语法：Python 用缩进表达代码块层次，避免了花括号噪声，也强制了代码排版一致性；同一代码块必须使用一致的空格数（官方推荐 4 空格）。",
        "函数是一等公民：函数可以赋值、传参、返回，配合 lambda、装饰器与闭包，构成函数式编程能力的基础。",
        "模块与包：每个 `.py` 文件是模块，目录加 `__init__.py` 是包；`import` 机制支持绝对导入、相对导入与命名空间包。",
        "异常处理：`try/except/finally` 与 `raise` 构成错误传播体系；`with` 语句通过上下文管理器（`__enter__/__exit__`）管理资源生命周期。",
    ],
    "theory": [
        "解释执行与字节码：CPython 先把源码编译为字节码（.pyc），再由虚拟机逐条执行。字节码是平台无关的中间表示，因此 Python 程序可以跨平台运行，但执行速度低于编译型语言；性能敏感路径可用 C 扩展或 Cython 加速。",
        "GIL（全局解释器锁）：CPython 的 GIL 保证同一时刻只有一个线程执行字节码，简化了内存管理，但限制了 CPU 密集型多线程并行；I/O 密集型任务通过线程切换获得并发，CPU 密集型任务应使用多进程（multiprocessing）或异步。",
        "引用计数与垃圾回收：Python 对象通过引用计数管理生命周期，循环引用由分代垃圾回收器（gc 模块）处理。理解这一模型可以解释“为什么局部变量及时释放内存”“为什么大对象需要 del 或作用域退出”。",
        "鸭子类型与协议：Python 依赖行为协议而非继承体系，例如实现 `__iter__` 与 `__next__` 的对象即可用于 `for` 循环。这一设计带来灵活性的同时，也要求开发者编写清晰的接口文档与类型注解。",
    ],
    "pitfalls": [
        ("可变默认参数", "`def f(x, lst=[])` 中默认列表在函数定义时创建一次，多次调用共享同一对象。最佳实践：默认值用 `None`，函数内创建新对象。"),
        ("浅拷贝陷阱", "`list.copy()`、切片与 `dict.copy()` 都是浅拷贝，嵌套可变对象仍共享。需要深拷贝时使用 `copy.deepcopy()`，或明确设计不可变结构。"),
        ("字符串拼接性能", "循环内使用 `+` 拼接字符串产生大量中间对象，复杂度为 O(n²)。最佳实践：使用列表收集后 `''.join()`。"),
        ("浮点精度", "二进制浮点无法精确表示 0.1，金额计算应使用 `decimal.Decimal` 或整数分。"),
        ("循环中修改列表", "遍历列表时删除或插入元素会导致跳过或重复。最佳实践：构造新列表或倒序遍历。"),
        ("全局变量滥用", "`global` 声明使函数产生隐藏依赖，难以测试。最佳实践：通过参数传递与返回值交换数据。"),
        ("异常吞掉", "`except: pass` 隐藏错误导致调试困难。最佳实践：捕获具体异常类型，记录日志，必要时重新抛出。"),
        ("时间与时区", "`datetime.now()` 返回本地时间，跨时区存储应使用 UTC。最佳实践：存储 UTC，展示时转本地。"),
        ("版本与依赖", "全局环境安装依赖导致版本冲突。最佳实践：使用 venv/uv/poetry 管理虚拟环境与锁定文件。"),
        ("性能过早优化", "在没有基准测试的情况下优化反而降低可读性。最佳实践：先 profile（cProfile）定位热点，再针对性优化。"),
    ],
    "practices": [
        "遵循 PEP 8 命名规范：模块与函数小写下划线，类用驼峰，常量全大写。",
        "使用类型注解（`def f(x: int) -> str`）配合 mypy/pyright 静态检查。",
        "函数保持单一职责并控制参数数量，超过 3 个参数考虑数据类。",
        "用 `if __name__ == \"__main__\":` 保护入口，保证模块可导入。",
        "资源使用 with 语句管理；日志使用 logging 模块而非 print。",
        "测试使用 pytest，覆盖正常、边界与异常路径。",
    ],
    "comparisons": [
        "Python 与 Java 对比：Python 动态类型开发快、代码短；Java 静态类型编译期检查强、适合大型长期项目。Python 的 GIL 限制多线程并行，Java 的线程模型更成熟。",
        "Python 与 Go 对比：Go 的 goroutine 与 channel 在并发编程上更直接，编译为单一二进制部署简单；Python 生态更丰富，AI 与数据领域占绝对优势。",
        "Python 2 与 Python 3 对比：Python 3 的 `print()` 函数、`str/bytes` 分离、整除语义 `//`、f-string 与类型注解是主要差异；新代码一律使用 Python 3。",
    ],
    "engineering": [
        "项目结构：src 布局（`src/` 下放包）与 flat 布局（包在根目录）各有优劣，配合 pyproject.toml 与 hatchling/setuptools 声明元数据。",
        "依赖管理：pyproject.toml 是 PEP 621 标准入口，uv 提供极快的解析与安装；锁定文件保证可复现构建。",
        "测试与 CI：pytest + coverage 度量，GitHub Actions 在矩阵（多版本 Python、多操作系统）上运行测试与 lint（ruff）。",
        "打包发布：构建 wheel（`python -m build`），发布到 PyPI；私有包可用内部索引或直接引用 git 依赖。",
    ],
    "case": [
        "需求：实现一个命令行文件统计工具，统计目录下各扩展名文件数量与总大小，支持递归。",
        "方案：使用 pathlib 遍历、collections.Counter 统计、argparse 解析参数，输出格式化报告。",
        "实现要点：用 `rglob('*')` 递归遍历；`suffix.lower()` 统一扩展名；大目录用生成器避免内存膨胀；异常（权限拒绝）单独捕获并记录。",
        "验证：对测试目录运行，核对数量与大小；对空目录与无权限目录验证边界行为；用 `time` 命令评估大目录性能。",
    ],
    "summary": [
        "Python 的核心竞争力是开发效率与生态广度，代价是运行性能与并发模型限制。",
        "类型注解、虚拟环境、测试与静态检查是现代 Python 工程的四条基线，缺一不可。",
        "理解解释执行、GIL 与内存模型，是解释 Python 行为异常（性能、并发、内存）的前提。",
    ],
    "refs": [
        "Python 官方文档：https://docs.python.org/zh-cn/3/",
        "PEP 8 样式指南：https://peps.python.org/pep-0008/",
        "Python 之禅（PEP 20）：https://peps.python.org/pep-0020/",
        "Python 类型注解指南（PEP 484）：https://peps.python.org/pep-0484/",
        "Python 打包用户指南：https://packaging.python.org/",
        "Real Python 教程站：https://realpython.com/",
    ],
    "more": [
        "Python 数据类型与内置容器，见 040-python 模块的基础文档。",
        "Python 异步编程（asyncio/FastAPI），见 040-python 模块的异步与 Web 文档。",
        "Python 数据分析（NumPy/Pandas），见 051-data-analysis 模块。",
        "Python 与数据库交互（SQLAlchemy），见 019-sql 模块相关文档。",
        "黑马程序员 Bilibili 空间（https://space.bilibili.com/37974444 ）提供 Python 全栈课程；尚硅谷 Bilibili 空间（https://space.bilibili.com/302417610 ）提供 Python 后端课程。",
    ],
    "supplement_examples": [
        "```python",
        "from pathlib import Path",
        "",
        "def count_files(root: Path) -> dict[str, int]:",
        "    \"\"\"统计目录下各扩展名文件数量。\"\"\"",
        "    counter: dict[str, int] = {}",
        "    for p in root.rglob('*'):  # 递归遍历所有路径",
        "        if p.is_file():",
        "            ext = p.suffix.lower() or '(无扩展名)'",
        "            counter[ext] = counter.get(ext, 0) + 1",
        "    return counter",
        "```",
        "讲解：`rglob('*')` 返回生成器，逐个处理文件避免一次性加载全部路径；`suffix.lower()` 统一大小写；`dict.get(ext, 0)` 实现计数累加。这是 Python 文件处理的通用骨架。",
    ],
    "deep_topics": [
        ("Python 对象模型与魔术方法", [
            "Python 的对象模型以“特殊方法”（dunder methods）为协议载体。`__init__` 负责初始化，`__new__` 负责创建；`__repr__` 与 `__str__` 控制展示；`__eq__` 与 `__hash__` 控制相等性与哈希。",
            "运算符重载同样基于协议：`__add__` 对应 +，`__lt__` 对应 <，`__getitem__` 对应下标访问。实现这些方法时，应保持与内置类型行为一致，例如 `__eq__` 返回布尔值、`__hash__` 与 `__eq__` 同步定义。",
            "上下文管理器协议（`__enter__/__exit__`）让自定义资源支持 with 语句；迭代器协议（`__iter__/__next__`）让自定义容器支持 for。掌握协议思维，就能写出与标准库无缝协作的类。",
            "属性协议（`__getattr__/__setattr__/__getattribute__`）与 `property` 装饰器提供属性访问控制；`__slots__` 声明固定属性，减少实例内存并提升属性访问速度。",
            "工程建议：优先使用 `dataclasses` 声明数据类，仅在需要深度定制时才手写特殊方法；每个特殊方法都应有明确的文档与测试。",
        ]),
        ("装饰器与闭包的原理", [
            "闭包是携带自由变量的函数：内层函数引用外层函数的变量，外层返回内层函数时，变量随函数一起保存。Python 用 `nonlocal` 声明需要修改的外层变量。",
            "装饰器是“接收函数并返回函数”的高阶函数，`@decorator` 语法等价于 `func = decorator(func)`。装饰器常用于日志、计时、鉴权、缓存。",
            "带参数的装饰器需要三层嵌套：最外层接收参数，中间层接收函数，内层包裹原函数。`functools.wraps` 复制原函数元信息，避免调试信息丢失。",
            "常见陷阱：装饰器只在导入时执行一次，若缓存结果会导致状态过期；装饰器堆叠顺序从下往上应用，从下往上执行。",
            "工程建议：装饰器保持薄层，复杂逻辑拆分为独立函数；使用 `functools.singledispatch` 实现单分派泛型，避免大量 isinstance 分支。",
        ]),
        ("生成器与内存优化", [
            "生成器函数使用 `yield` 逐次产出值，保存执行状态，下次调用从断点继续。与列表相比，生成器不一次性占用内存，适合大文件、无限序列与流式处理。",
            "生成器表达式 `(x * x for x in range(10))` 是惰性求值的列表推导变体；`yield from` 委托子生成器，简化递归生成。",
            "协程与生成器同源：`send()` 向生成器传入值，`throw()` 注入异常，`close()` 终止。asyncio 的事件循环正是基于这一机制实现异步任务调度。",
            "流水线模式：多个生成器串联（如读取行、过滤、转换、输出），每个环节独立可测，内存占用恒定。",
            "工程建议：不确定数据量时默认用生成器；需要随机访问或多遍遍历时改用列表；用 `itertools` 组合生成器避免重复造轮子。",
        ]),
    ],
}


def _lang(k, label, hint, axes, history, history_tail, definitions, theory, pitfalls,
          practices, comparisons, engineering, case, summary, refs, more,
          supplement, deep):
    return {
        "label": label,
        "related_title_hint": hint,
        "axes": axes,
        "history": history,
        "history_tail": history_tail,
        "definitions": definitions,
        "theory": theory,
        "pitfalls": pitfalls,
        "practices": practices,
        "comparisons": comparisons,
        "engineering": engineering,
        "case": case,
        "summary": summary,
        "refs": refs,
        "more": more,
        "supplement_examples": supplement,
        "deep_topics": deep,
    }


KB_LANG["java"] = _lang(
    "java", "Java", "JVM、集合框架、并发、Spring 生态",
    [
        "能够说出 Java 的编译执行模型（javac 到字节码，JVM 解释与 JIT）。",
        "能够解释面向对象三大特性与 JVM 内存区域的职责。",
        "能够编写类、接口、集合操作与异常处理的完整程序。",
        "能够分析 Java 与 C++、Go 在内存管理与并发模型上的差异。",
        "能够评价不同集合、并发工具与框架的适用场景。",
        "能够组合 Spring 生态设计企业级应用。",
    ],
    [
        "Java 由 James Gosling 领导的 Sun 团队于 1995 年发布，口号“一次编写，到处运行”依托 JVM 字节码实现跨平台。2006 年 Sun 将 Java 开源（OpenJDK），2010 年 Oracle 收购 Sun 后 Java 进入新的治理阶段。",
        "Java 的版本节奏在 2017 年后改为每半年一个特性版本、每两年一个 LTS（长期支持）版本。当前主流 LTS 包括 Java 11、17、21 与 25；Java 21 引入虚拟线程（Project Loom 成果），显著降低高并发服务的线程成本。",
        "Java 生态以 Spring 家族为核心：Spring Boot 简化配置与部署，Spring Cloud 提供微服务组件；构建工具从 Maven 演进到 Gradle；JVM 语言（Kotlin、Scala、Groovy）与 Java 共存互操作。",
        "Android 开发早期使用 Java，2019 年后官方转向 Kotlin-first，但 Java 仍是服务端领域（尤其是金融、电商等企业系统）的中坚力量。",
    ],
    [
        "理解 Java 版本与 LTS 机制，是工程选型的起点：生产环境优先 LTS，新特性（如虚拟线程）可以在受控场景评估后引入。",
    ],
    [
        "JVM 与字节码：`javac` 把 .java 编译为 .class 字节码，JVM 加载、校验并执行；热点代码由 JIT（如 C2）编译为机器码，解释与编译结合实现启动速度与峰值性能的平衡。",
        "面向对象：封装（访问控制）、继承（extends/implements）与多态（重载/重写）是 Java 的类型系统支柱；接口默认方法（Java 8）与密封类（Java 17）持续演进表达能力。",
        "异常体系：受检异常（checked）编译期强制处理，非受检异常（RuntimeException）运行时抛出；try-with-resources 自动关闭资源。",
        "泛型与擦除：Java 泛型在编译期检查后擦除类型参数，运行时无泛型信息；这解释了 `List<String>` 与 `List<Integer>` 的 Class 相同，以及通配符 `? extends` 的逆变协变规则。",
    ],
    [
        "JVM 内存模型：堆（新生代/老年代）、元空间、虚拟机栈、本地方法栈与程序计数器；GC 从 CMS 演进到 G1（默认）、ZGC（超低延迟），理解分代收集是调优前提。",
        "并发工具：synchronized 与 JUC（java.util.concurrent）的锁、并发容器、线程池、CompletableFuture 构成并发工具箱；Java 21 的虚拟线程让“每任务一线程”成为可能。",
        "类加载机制：双亲委派模型保证类唯一性，SPI（ServiceLoader）打破委派实现扩展；自定义类加载器是热部署与隔离的基础。",
        "反射与注解：反射在运行时检查类结构，注解提供元数据；Spring 的依赖注入与 AOP 均基于这些机制，但反射有性能与安全成本。",
    ],
    [
        ("equals 与 hashCode 不一致", "违反约定导致 HashMap 查找失效。重写 equals 必须同步重写 hashCode，且保证相等对象哈希一致。"),
        ("集合遍历时修改", "`for-each` 中调用 `list.remove` 抛 ConcurrentModificationException。使用 Iterator.remove 或收集后批量删除。"),
        ("字符串用 == 比较", "`==` 比较引用而非内容；字符串应使用 `equals`，并优先字符串常量池与 `StringBuilder` 拼接。"),
        ("整数缓存误判", "`Integer` 在 -128~127 间缓存，`==` 可能为 true，超出范围为 false。包装类型比较一律用 equals。"),
        ("线程安全误用", "`SimpleDateFormat` 非线程安全，多线程格式化出错。使用 `DateTimeFormatter`（不可变）或 ThreadLocal。"),
        ("资源泄漏", "忘记关闭连接与流。使用 try-with-resources 或确保 finally 关闭。"),
        ("空指针", "链式调用未判空。使用 Optional、Objects.requireNonNull 与防御式检查。"),
        ("大对象长时间存活", "导致老年代增长与 Full GC。评估对象生命周期，及时释放引用，必要时使用弱引用。"),
        ("魔法数字与重复代码", "可读性与维护性下降。使用常量、枚举与抽取方法。"),
        ("忽略编译告警", "未检查类型转换与废弃 API 隐藏问题。开启 -Xlint 并保持零告警。"),
    ],
    [
        "遵循 Java 命名规范：类名驼峰、常量全大写、包名小写域名反写。",
        "面向接口编程，依赖注入优先于直接 new。",
        "不可变对象优先：final 字段 + 防御性拷贝。",
        "集合返回只读视图，避免外部修改内部状态。",
        "日志使用 SLF4J 门面 + 占位符，避免字符串拼接。",
        "测试使用 JUnit 5 + AssertJ，按 given/when/then 组织。",
    ],
    [
        "Java 与 C++：Java 无指针算术、自动 GC、跨平台；C++ 可精细控制内存与性能，适合系统级开发。Java 开发效率高，C++ 性能上限高。",
        "Java 与 Go：Java 生态成熟、类型系统与工具链完备；Go 语法简单、并发原生、部署为单一二进制。服务端选型取决于团队与生态。",
        "Java 8 与 Java 21：lambda/Stream（8）与虚拟线程/模式匹配（21）代表两个时代；新项目应基于 17+ 使用现代 API。",
    ],
    [
        "Maven 项目结构：src/main/java、src/test/java 与 pom.xml；依赖坐标（groupId/artifactId/version）从中央仓库解析。",
        "Spring Boot 分层：Controller（HTTP 层）、Service（业务层）、Repository（数据层）；DTO 与实体分离防止内部结构泄漏。",
        "配置管理：application.yml + profile（dev/prod）+ 配置中心；敏感信息走环境变量或 Secret。",
        "可观测性：actuator 健康端点、Micrometer 指标、分布式追踪（OpenTelemetry）构成生产基线。",
    ],
    [
        "需求：实现订单服务，支持创建订单、查询列表与状态流转。",
        "方案：Spring Boot 3 + JPA + H2（演示），Controller-Service-Repository 三层。",
        "实现要点：订单状态用枚举；金额用 BigDecimal；创建订单在事务内完成库存校验与扣减；接口返回 DTO。",
        "验证：JUnit 测试服务层事务回滚；MockMvc 测试 HTTP 层；压测关注吞吐与延迟。",
    ],
    [
        "Java 的竞争力来自 JVM 生态的深度与广度，选型时应优先考虑团队存量技能与生态需求。",
        "内存、并发与类加载三大机制是 Java 进阶的分水岭，理解它们才能解决线上疑难问题。",
        "工程化基线：LTS 版本、依赖锁定、静态检查、单元测试与可观测性。",
    ],
    [
        "Oracle Java 官方文档：https://docs.oracle.com/en/java/",
        "OpenJDK 项目：https://openjdk.org/",
        "Java 语言规范：https://docs.oracle.com/javase/specs/",
        "Spring 官方文档：https://spring.io/projects/spring-boot",
        "Baeldung 教程站：https://www.baeldung.com/",
        "Maven 官方文档：https://maven.apache.org/guides/",
    ],
    [
        "Java 并发与 JUC，见 013-java 模块并发文档。",
        "JVM 内存与 GC 调优，见 013-java 模块 JVM 文档。",
        "Spring Boot 微服务与 Kubernetes，见 013-java/041-JavaKubernetes 文档。",
        "数据库访问（JDBC/JPA），见 019-sql 模块相关文档。",
        "黑马程序员 Bilibili 空间（https://space.bilibili.com/37974444 ）提供 Java 全栈课程；尚硅谷 Bilibili 空间（https://space.bilibili.com/302417610 ）提供 Java 进阶课程。",
    ],
    [
        "```java",
        "// 泛型工具：类型安全的取最小值",
        "public static <T extends Comparable<T>> T minOf(T a, T b) {",
        "    return a.compareTo(b) <= 0 ? a : b;",
        "}",
        "```",
        "讲解：`<T extends Comparable<T>>` 约束 T 必须可比较，编译期保证 `compareTo` 可用；返回值类型与入参一致，避免运行时强转。",
    ],
    [
        ("Java 集合框架源码级分析", [
            "HashMap 在 Java 8+ 由数组 + 链表 + 红黑树组成：哈希桶冲突超过 8 且容量不小于 64 时树化；扩容按 2 的幂进行，通过 `(n-1) & hash` 定位桶。",
            "ConcurrentHashMap 采用 CAS + synchronized 锁桶（Java 8 实现），读操作无锁；与 HashTable 的全表锁相比并发度大幅提升。",
            "ArrayList 扩容 1.5 倍并复制数组；LinkedList 每个节点有前后指针；LinkedList 的随机访问是 O(n)，顺序插入删除是 O(1)。",
            "PriorityQueue 是小顶堆结构，offer/poll 为 O(log n)；TreeMap/TreeSet 基于红黑树，key 有序。",
            "工程建议：按操作特征选型——随机访问用 ArrayList，频繁头尾操作用 ArrayDeque，排序键用 TreeMap，高并发用 ConcurrentHashMap。",
        ]),
        ("JVM 垃圾回收与调优", [
            "分代假说：大多数对象朝生夕灭。新生代（Eden + Survivor）采用复制算法，老年代采用标记-整理或并发标记；GC Roots 可达性分析决定存活对象。",
            "G1 把堆划分为 Region，跟踪每个 Region 的回收价值，优先回收收益最高的区域；ZGC 使用染色指针与读屏障实现亚毫秒级暂停。",
            "调优参数：-Xms/-Xmx 设置堆，-XX:MaxMetaspaceSize 限制元空间，-XX:MaxGCPauseMillis 设置 G1 目标停顿。",
            "调优流程：先用 GC 日志与 JFR 观察，再调整堆与 GC 策略；避免盲目复制网上参数。容器环境注意 -XX:MaxRAMPercentage。",
        ]),
        ("虚拟线程与高并发编程", [
            "Java 21 的虚拟线程（Virtual Threads）由 JVM 调度，占用内存远小于平台线程，支持百万级并发任务；适合 I/O 密集场景。",
            "使用 Executors.newVirtualThreadPerTaskExecutor() 创建线程池；阻塞 I/O 时虚拟线程自动让出载体线程。",
            "注意：synchronized 块内阻塞会固定载体线程；尽量使用 ReentrantLock 或避免在锁内阻塞。",
            "虚拟线程不是万能：CPU 密集任务仍受核心数限制；线程本地变量（ThreadLocal）在虚拟线程下成本更高。",
        ]),
    ],
)


def _compact(label, hint, axes, history, theory, pitfalls, practices, comparisons,
             engineering, case, summary, refs, more, deep):
    """紧凑模块知识库条目：definitions 从 theory 中提取。"""
    return _lang(
        None, label, hint, axes,
        history,
        [],
        theory[:3],
        theory,
        pitfalls,
        practices,
        comparisons,
        engineering,
        case,
        summary,
        refs,
        more,
        [],
        deep,
    )


KB_LANG["kotlin"] = _compact(
    "Kotlin", "类型推断、空安全、协程、KMP",
    [
        "能够说出 val/var、空安全操作符与 when 表达式的语法。",
        "能够解释 Kotlin 与 Java 互操作的机制与平台类型概念。",
        "能够编写数据类、扩展函数与协程代码。",
        "能够分析空安全、智能转换与协程调度原理。",
        "能够评价 Kotlin 在 Android、服务端与多平台场景的适用性。",
        "能够组合 Compose 与协程设计跨平台应用。",
    ],
    [
        "Kotlin 由 JetBrains 于 2010 年开始研发，2016 年发布 1.0，定位是“更现代的 JVM 语言”：减少样板代码、消灭空指针、增强函数式能力，同时与 Java 100% 互操作。",
        "2017 年 Google 宣布 Kotlin 成为 Android 一级语言，2019 年确立 Kotlin-first 政策；2023 年 Kotlin 2.0 的 K2 编译器显著提升编译速度与类型推导。",
        "Kotlin Multiplatform（KMP）支持 JVM、Android、iOS、WebAssembly 等目标，配合 Compose Multiplatform 实现共享 UI 与业务逻辑，是 JetBrains 的长期战略方向。",
    ],
    [
        "空安全：类型系统区分 `String` 与 `String?`，编译期强制处理可空值；`?.` 短路、`?:` 提供默认、`!!` 显式断言，三者覆盖所有空值处理模式。",
        "智能转换：`is` 检查后在不可变上下文中自动转换类型，减少显式强转；`as?` 安全转换失败返回 null。",
        "协程：挂起函数（suspend）与调度器（Dispatchers.Main/IO/Default）实现非阻塞并发，结构化并发保证作用域内任务可取消。",
        "扩展函数与属性：在不修改原类的情况下为类添加行为，是 Kotlin 标准库（如集合操作）的基石。",
    ],
    [
        ("val 误当不可变对象", "val 只约束引用；对象内部仍可变。需要深层不可变时使用只读集合与 data class 副本。"),
        ("滥用 !!", "非空断言重新引入 NPE。业务代码用 ?: 与 ?. 替代，!! 仅限互操作边界。"),
        ("协程作用域泄漏", "在 Activity/ViewModel 外启动协程导致任务悬挂。使用 viewModelScope 或 lifecycleScope。"),
        ("扩展函数命名冲突", "同签名扩展函数按导入优先级解析，易混淆。使用明确包名与独特命名。"),
        ("data class 相等性误判", "相等性基于所有主构造属性；集合属性（List）使用引用相等。注意复制副本的共享引用。"),
        ("挂起函数在非协程调用", "suspend 函数只能在协程或其他挂起函数中调用；需要桥接时用 runBlocking（慎用）或回调封装。"),
    ],
    [
        "优先 val 与不可变集合，减少可变状态面。",
        "用数据类表达数据，用密封类表达受限层级。",
        "协程遵循结构化并发，子任务随父作用域取消。",
        "接口默认实现与扩展函数分离“数据”与“行为”。",
        "使用 ktlint/detekt 保持风格一致。",
    ],
    [
        "Kotlin 与 Java：Kotlin 代码更短、空安全更强；Java 生态工具链更传统。两者互操作，可渐进迁移。",
        "Kotlin 与 Swift：Kotlin 服务端/Android 与 Swift iOS 各自主导；KMP 让业务逻辑共享成为可能。",
        "协程与线程：协程是用户态调度，数量可达百万级；线程是内核态，切换成本高。",
    ],
    [
        "Android 项目：Gradle Kotlin DSL 构建，Compose 声明式 UI，ViewModel + StateFlow 管理状态。",
        "服务端：Ktor 轻量异步框架，或 Spring Boot 使用 Kotlin 语言特性。",
        "多平台：共享模块（commonMain）放业务逻辑，平台模块（androidMain/iosMain）放平台 API。",
    ],
    [
        "需求：实现跨平台（Android/iOS）的待办事项应用核心逻辑。",
        "方案：KMP 共享数据层与状态管理，平台层仅做 UI 渲染。",
        "要点：Room/SQLDelight 做本地存储；协程处理异步；expect/actual 声明平台差异。",
        "验证：共享模块单元测试 + 平台端集成测试。",
    ],
    [
        "Kotlin 的价值在于“现代化而不割裂”：保留 JVM 生态，同时提供现代语言特性。",
        "空安全与协程是 Kotlin 的两大支柱，工程代码应默认使用。",
        "KMP 适合业务逻辑共享，UI 层按平台选择 Compose 或原生。",
    ],
    [
        "Kotlin 官方文档：https://kotlinlang.org/docs/home.html",
        "Kotlin 协程指南：https://kotlinlang.org/docs/coroutines-guide.html",
        "Compose Multiplatform：https://www.jetbrains.com/compose-multiplatform/",
        "Ktor 框架：https://ktor.io/",
        "Android 开发者文档：https://developer.android.com/kotlin",
    ],
    [
        "Kotlin 基础语法精讲，见 014-kotlin/002-KotlinBasicSyntax 文档。",
        "协程与 Flow，见 014-kotlin 模块协程文档。",
        "Android 与 HarmonyOS 应用开发，见 018-harmonyos 模块。",
        "黑马程序员 Bilibili 空间（https://space.bilibili.com/37974444 ）提供 Kotlin 课程。",
    ],
    [
        ("协程调度与 Flow 背压", [
            "协程调度器决定线程切换：Dispatchers.Main 走 Android 主线程，IO 用于阻塞 I/O，Default 用于 CPU 密集；withContext 切换上下文而不阻塞调用方。",
            "Flow 是冷流：每次收集重新执行；`flowOn` 切换上游上下文，`buffer` 缓冲背压，`conflate` 丢弃中间值。",
            "StateFlow 持有最新值并去重，适合 UI 状态；SharedFlow 支持多订阅与事件广播。",
            "取消协作：挂起点检查取消状态并抛出 CancellationException；耗时计算需周期调用 ensureActive。",
        ]),
        ("KMP 多平台架构", [
            "KMP 项目以 kotlin-multiplatform 插件定义 targets（jvm、iosArm64、js 等）；commonMain 中 expect 声明，平台源集 actual 实现。",
            "依赖管理：commonMain 使用 kotlinx 库（coroutines、serialization、datetime），平台差异库放对应源集。",
            "与 Compose Multiplatform 组合时，UI 逻辑共享、平台能力通过 expect/actual 隔离。",
            "构建产物：Android 输出 AAR，iOS 输出 framework；通过 CocoaPods 或 Swift Package 集成。",
        ]),
    ],
)

KB_LANG["go"] = _compact(
    "Go", "goroutine、channel、内存模型、标准库",
    [
        "能够说出 Go 的包、函数、结构体、接口与错误处理基本语法。",
        "能够解释 goroutine 调度、channel 通信与内存模型。",
        "能够编写并发程序、HTTP 服务与命令行工具。",
        "能够分析数据竞争、死锁与性能瓶颈。",
        "能够评价 Go 与 Java、Python 在不同场景的取舍。",
        "能够设计完整的微服务与云原生应用。",
    ],
    [
        "Go 由 Google 的 Robert Griesemer、Rob Pike 与 Ken Thompson 于 2009 年发布，设计目标是解决大规模分布式系统的工程痛点：编译慢、依赖混乱、并发难写。",
        "Go 1.0 于 2012 年发布，此后严格保持向后兼容（Go 1 兼容性承诺）；约每半年发布一个小版本，1.21 起引入工具链管理（toolchain 指令）与内置测试 fuzzing。",
        "Go 在云原生领域成为事实标准：Docker、Kubernetes、Prometheus、etcd 等核心项目均用 Go 编写；泛型在 1.18 加入，1.21+ 的 slices/maps 标准包补齐泛型工具。",
    ],
    [
        "goroutine 与调度：goroutine 是用户态轻量线程，由 GMP 调度器（Goroutine、Machine、Processor）多路复用到内核线程；创建成本约 2KB 栈，支持百万级并发。",
        "channel 与 select：channel 是类型化通信管道，`<-` 发送/接收；select 多路等待；“不要通过共享内存通信，而要通过通信共享内存”是 Go 并发哲学。",
        "内存模型：happens-before 关系由 channel、sync 原语与 atomic 建立；`go test -race` 用 ThreadSanitizer 检测数据竞争。",
        "错误处理：Go 用多返回值显式处理错误（`if err != nil`），error 是接口；panic/recover 仅用于不可恢复错误。",
    ],
    [
        ("忽略错误返回值", "错误被静默丢弃导致故障难查。显式检查并包装上下文（fmt.Errorf + %w）。"),
        ("goroutine 泄漏", "channel 无接收者或循环启动 goroutine 导致资源泄漏。使用 context 取消与 WaitGroup 收口。"),
        ("共享变量竞争", "多个 goroutine 读写同一变量未同步。使用 mutex、atomic 或改为 channel 传递。"),
        ("defer 在循环中累积", "defer 在函数返回时执行，循环内 defer 延迟大量资源释放。将循环体提取为函数。"),
        ("切片共享底层数组", "append 可能修改共享数组，产生隐蔽 bug。需要独立数据时用 copy 或完整切片表达式。"),
        ("map 并发读写", "map 非并发安全，并发写 panic。使用 sync.Map 或加锁。"),
        ("指针逃逸与性能误判", "过早优化影响可读性。先用 benchmark 与 pprof 定位热点。"),
        ("超时控制缺失", "网络请求无超时导致 goroutine 悬挂。使用 http.Client.Timeout 与 context.WithTimeout。"),
    ],
    [
        "使用 gofmt 统一格式，go vet 静态检查。",
        "错误处理显式且带上下文，不使用 panic 做业务控制。",
        "并发入口使用 context 传递取消与超时。",
        "接口尽量小，函数参数按需接收。",
        "每次提交前运行 go test -race ./...。",
    ],
    [
        "Go 与 Java：Go 编译快、部署简单（静态二进制）、并发原语原生；Java 生态更丰富、虚拟线程补足并发短板。",
        "Go 与 Python：Go 性能高、类型安全；Python 开发快、AI 生态强。",
        "goroutine 与线程：goroutine 用户态调度、栈动态增长；线程内核态、栈固定。",
    ],
    [
        "标准项目布局：cmd/（可执行入口）、internal/（私有包）、pkg/（对外库）；单一 main 包保持薄。",
        "HTTP 服务：net/http 标准库 + 中间件模式；路由可用 Go 1.22+ 的 method pattern。",
        "配置与日志：环境变量 + 结构体映射；log/slog（1.21+）结构化日志。",
        "部署：多阶段 Dockerfile 构建静态二进制，镜像可小至几十 MB。",
    ],
    [
        "需求：实现并发安全的限流器与统计服务。",
        "方案：atomic 计数 + channel 令牌桶 + net/http 中间件。",
        "要点：原子操作更新峰值；context 控制请求超时；/metrics 暴露计数。",
        "验证：go test -race 检测竞争；压测验证限流准确率。",
    ],
    [
        "Go 的核心优势是简单与并发：语法规模小、工具链统一、并发模型清晰。",
        "工程基线：race 检测、context 传递、显式错误处理。",
        "云原生是 Go 的主场，微服务与基础设施选型应优先考虑。",
    ],
    [
        "Go 官方文档：https://go.dev/doc/",
        "Go 内存模型：https://go.dev/ref/mem",
        "Effective Go：https://go.dev/doc/effective_go",
        "Go 标准库：https://pkg.go.dev/std",
        "Go 官方博客：https://go.dev/blog/",
    ],
    [
        "Go 并发与 channel，见 016-go 模块并发文档。",
        "Go 原子操作与竞争检测，见 016-go/058-RaceDetectionAtomic 文档。",
        "云原生与 Kubernetes，见 031-devops 模块。",
        "黑马程序员 Bilibili 空间（https://space.bilibili.com/37974444 ）提供 Go 课程。",
    ],
    [
        ("Go 调度器 GMP 模型", [
            "G（Goroutine）是任务单元，M（Machine）是内核线程，P（Processor）是执行上下文与本地队列。P 的数量默认等于 CPU 核心数（GOMAXPROCS）。",
            "调度事件：go 语句创建 G 入本地队列；本地队列满时偷取（work stealing）；阻塞系统调用时 M 与 P 解绑，P 被其他 M 接管。",
            "网络 I/O 通过 netpoller 事件驱动，阻塞的 G 挂起而非占用线程，因此 Go 的并发 I/O 效率极高。",
            "理解 GMP 可以解释：为什么 goroutine 数量不等于并行度；为什么 GOMAXPROCS 影响吞吐；为什么 CPU 密集任务要限制并发数。",
        ]),
        ("Go 泛型与类型约束", [
            "Go 1.18 引入类型参数 `[T any]` 与约束接口；`~int` 表示底层类型为 int 的类型集合，`comparable` 约束可比较类型。",
            "泛型函数示例：`func Map[T, U any](s []T, f func(T) U) []U`；泛型类型示例：`type Set[T comparable] map[T]struct{}`。",
            "约束中的类型集（union）与接口方法并存；1.21 的 slices/maps 标准包提供泛型工具。",
            "工程建议：能用接口解决的不必泛型；泛型用于容器、算法与类型安全抽象。",
        ]),
    ],
)

KB_LANG["c"] = _compact(
    "C", "指针、内存管理、预处理器、标准库",
    [
        "能够说出 C 的变量、函数、指针、数组、结构体与预处理语法。",
        "能够解释指针与内存地址、栈与堆、编译链接过程。",
        "能够编写系统工具、数据结构与嵌入式程序。",
        "能够分析内存泄漏、缓冲区溢出与未定义行为。",
        "能够评价 C 与其他语言在系统编程中的取舍。",
        "能够设计可移植、可维护的 C 库与模块。",
    ],
    [
        "C 由 Dennis Ritchie 于 1972 年在贝尔实验室为 Unix 开发，是系统编程的基石语言：操作系统、编译器、嵌入式固件均以 C 为主。",
        "C89（ANSI C）统一方言，C99 引入变长数组与 // 注释，C11 增加泛型选择与线程支持，C17 为缺陷修复版，C23（2024 年正式发布）引入 constexpr、属性、显式枚举底层类型等现代化特性。",
        "C 的哲学是“信任程序员”：提供指针与内存操作的全部能力，同时把正确性责任交给开发者；这一设计成就了性能上限，也带来内存安全风险，催生了 Rust 等后继语言。",
    ],
    [
        "指针：指针保存变量地址，`&` 取地址、`*` 解引用；指针算术与数组名退化规则（数组名作为实参退化为首元素指针）是 C 的经典难点。",
        "内存管理：栈内存自动释放，堆内存由 malloc/calloc/realloc/free 管理；所有权责任（谁分配谁释放）必须显式约定。",
        "预处理器：#include/#define/#ifdef 在编译前文本处理；宏展开有副作用与优先级风险，函数式宏参数必须加括号。",
        "编译链接：预处理 -> 编译 -> 汇编 -> 链接；头文件声明接口，源文件实现；静态库与动态库（.a/.so/.dll）决定部署形态。",
    ],
    [
        ("缓冲区溢出", "gets/strcpy 不检查边界导致安全漏洞。使用 fgets/strncpy（注意截断语义）或安全库。"),
        ("内存泄漏", "malloc 后未 free。设计清晰的所有权规则，配合 Valgrind/ASan 检测。"),
        ("悬垂指针", "free 后继续使用指针。释放后置 NULL，并约定使用前检查。"),
        ("未定义行为", "有符号溢出、数组越界、除零等行为不可预测。开启 -Wall -Wextra -fsanitize=undefined 检测。"),
        ("宏副作用", "`#define SQUARE(x) x*x` 在 `SQUARE(a+b)` 时出错。参数加括号或用内联函数。"),
        ("字符串字面量修改", "修改字符串字面量是未定义行为。需要修改时用字符数组。"),
        ("忘记初始化", "局部变量未初始化读随机值。声明即初始化。"),
        ("类型混用", "有符号与无符号比较产生隐式转换。注意 -Wsign-compare 告警。"),
    ],
    [
        "声明即初始化，指针必须有效或为 NULL。",
        "资源分配与释放成对出现，封装为函数。",
        "数组访问使用边界检查（调试版本启用断言）。",
        "头文件加 include guard，声明与实现分离。",
        "编译开启 -Wall -Wextra -Werror（开发阶段）。",
    ],
    [
        "C 与 C++：C++ 是 C 的超集扩展，支持类、模板、异常与 RAII；C 更简单直接，适合嵌入式与纯系统编程。",
        "C 与 Rust：Rust 在编译期保证内存安全（所有权/借用）；C 灵活但需要人工保证安全。新系统项目可评估 Rust。",
        "C89 与 C23：C23 带来 constexpr、attributes、二进制字面量等，现代化程度提升但仍保持兼容。",
    ],
    [
        "模块化：头文件定义接口（结构体前向声明、函数原型），源文件实现；内部函数用 static 隐藏。",
        "错误处理：函数返回错误码或状态枚举，输出参数传结果；文档化调用方责任。",
        "构建：Makefile/CMake 管理编译单元与依赖；编译选项区分 debug/release。",
        "测试：断言 + 单元测试框架（Unity/CMocka），配合 AddressSanitizer。",
    ],
    [
        "需求：实现动态数组容器（vector），支持追加、按索引访问与释放。",
        "方案：结构体封装 data/capacity/size，API 提供 create/destroy/push/at。",
        "要点：扩容按 2 倍增长；越界返回错误码；所有分配路径成对释放。",
        "验证：ASan 检查泄漏与越界；边界用例（空容器、满容量扩容）。",
    ],
    [
        "C 的价值在于极致的控制力与可移植性，代价是内存安全责任完全在开发者。",
        "指针、内存、未定义行为三大主题决定 C 代码质量。",
        "现代 C 工程应结合静态分析、消毒器与测试，把人为错误降到最低。",
    ],
    [
        "cppreference C 文档：https://zh.cppreference.com/w/c",
        "C 标准草案：https://www.open-std.org/jtc1/sc22/wg14/",
        "GCC 官方文档：https://gcc.gnu.org/onlinedocs/",
        "Linux man pages：https://man7.org/linux/man-pages/",
        "C 语言常见误解：https://www.yodaiken.com/",
    ],
    [
        "C 指针与数组深入，见 025-c 模块指针文档。",
        "C 枚举与 typedef，见 025-c/007-EnumTypedef 文档。",
        "C++ 面向对象与模板，见 026-cpp 模块。",
        "嵌入式 C 与硬件交互，见 035-iot 模块。",
        "尚硅谷 Bilibili 空间（https://space.bilibili.com/302417610 ）提供 C 语言课程。",
    ],
    [
        ("指针与数组的等价与差异", [
            "数组名是常量地址（不可赋值），`sizeof(arr)` 返回整个数组字节数；作为函数实参时退化为首元素指针，`sizeof` 变为指针大小。",
            "指针算术：`p + i` 移动 i 个元素；二维数组 `int a[3][4]` 中 `a` 类型为 `int (*)[4]`，`a[i][j]` 等价 `*(*(a+i)+j)`。",
            "函数指针：`int (*fp)(int)` 可赋值、传参、构成回调表；typedef 简化声明。",
            "const 位置语义：`const int *p`（指向常量的指针）与 `int *const p`（常量指针）不同，从内向外读声明可避免混淆。",
        ]),
        ("C 内存布局与对齐", [
            "进程内存分为代码段、数据段、BSS、堆、栈；栈向下增长，堆向上增长，中间为空洞。",
            "结构体成员按对齐规则布局：成员偏移为自身对齐值的倍数，结构体大小为最大对齐值的倍数；重排成员可减少 padding。",
            "位域（bit-field）依赖编译器布局，序列化跨平台数据时应使用显式移位。",
            "理解布局有助于调试（指针偏移、序列化、共享内存）与优化（缓存友好结构体）。",
        ]),
    ],
)

KB_LANG["cpp"] = _compact(
    "C++", "RAII、移动语义、模板、STL",
    [
        "能够说出 C++ 的类、继承、重载、模板与 STL 容器基本语法。",
        "能够解释 RAII、拷贝/移动语义、虚函数与模板实例化。",
        "能够编写现代 C++（C++17/20）的类与泛型代码。",
        "能够分析生命周期、未定义行为与性能特征。",
        "能够评价 C++ 与 Rust、Java 在系统编程中的取舍。",
        "能够设计高性能、可维护的 C++ 库与应用。",
    ],
    [
        "C++ 由 Bjarne Stroustrup 于 1979 年开始在贝尔实验室开发（原名 C with Classes），1983 年更名 C++，1998 年 C++98 首次标准化。",
        "C++11 是语言转折点：右值引用、auto、lambda、智能指针、并发内存模型让现代 C++ 写法定型；C++14/17 补充泛型 lambda、if constexpr、折叠表达式；C++20 引入 concepts、协程、模块与范围库；C++23 继续完善。",
        "现代 C++ 的核心口号是“资源安全”：RAII + 智能指针替代裸 new/delete，异常与错误码按场景选择；Rust 的出现促使 C++ 社区更重视内存安全工具（如 profile 指南、sanitizer）。",
    ],
    [
        "RAII：资源在构造函数获取、析构函数释放，栈对象离开作用域自动清理；智能指针（unique_ptr/shared_ptr/weak_ptr）把所有权编码进类型。",
        "移动语义：右值引用 `&&` 与 std::move 转移资源所有权，避免深拷贝；移动后对象处于“合法但未指定”状态。",
        "虚函数与多态：virtual 实现动态绑定，vtable 是运行时分派机制；final/override 关键字防止误用；基类析构函数应为 virtual。",
        "模板与泛型：模板编译期实例化，实现静态多态；concepts（C++20）约束类型接口；模板元编程在编译期计算类型与常量。",
    ],
    [
        ("裸 new/delete", "易泄漏与重复释放。使用 make_unique/make_shared 与栈对象。"),
        ("引用悬垂", "返回局部变量引用或存储容器元素引用后容器扩容。理解生命周期，必要时用值或智能指针。"),
        ("迭代器失效", "vector 扩容使迭代器失效。避免在遍历时修改容器，或改用索引/新容器。"),
        ("虚析构缺失", "通过基类指针删除派生对象时未调用派生析构。基类析构声明为 virtual。"),
        ("std::move 后使用对象", "移动后对象状态未指定。移动后只赋值或销毁，不再读取。"),
        ("隐式转换意外", "单参数构造函数产生隐式转换。标记 explicit。"),
        ("异常安全", "异常中途抛出导致资源泄漏或不变量破坏。使用 RAII 与强异常保证设计。"),
        ("宏替代常量", "无类型检查。用 constexpr 与 enum class。"),
    ],
    [
        "默认使用现代特性：auto、范围 for、智能指针、constexpr。",
        "接口用抽象类与 concepts 表达，实现细节隐藏。",
        "容器优先 STL，算法用 <algorithm> 而非手写循环。",
        "编译开启 -Wall -Wextra -Wpedantic，配合 sanitizer。",
        "代码评审关注所有权与生命周期。",
    ],
    [
        "C++ 与 C：C++ 支持面向对象与泛型、RAII 与标准库；C 更简单，适合纯系统与嵌入式。",
        "C++ 与 Rust：Rust 编译期保证内存安全，所有权模型严格；C++ 灵活但依赖纪律。性能相近，安全性 Rust 更强。",
        "C++11 与 C++20：concepts、协程、范围库代表现代 C++ 方向；新代码以 C++20 为基线。",
    ],
    [
        "CMake 构建：target 化组织（add_library/add_executable），导出接口与安装规则。",
        "依赖管理：Conan/vcpkg 管理第三方库；预编译头与 ccache 加速构建。",
        "测试与工具：GoogleTest 单测、ASan/UBSan 检测、clang-tidy 静态分析。",
        "性能：profiler（perf、VTune）定位热点；缓存友好数据结构与无锁并发按需引入。",
    ],
    [
        "需求：实现线程安全的对象池，支持获取/归还与自动扩容。",
        "方案：unique_ptr 管理池中对象，mutex + condition_variable 同步，工厂函数创建新对象。",
        "要点：RAII 包装归还（析构自动回池）；超时等待避免死锁；容量上限保护。",
        "验证：TSan 检测数据竞争；benchmark 对比加锁与无锁方案。",
    ],
    [
        "C++ 的核心是“零开销抽象”：高级表达不牺牲性能，但需要开发者理解底层机制。",
        "RAII 与移动语义是现代 C++ 的基石，资源安全靠类型系统与纪律共同保证。",
        "模板与 concepts 让泛型代码可读、可约束；sanitizer 是质量保障标配。",
    ],
    [
        "cppreference C++ 文档：https://zh.cppreference.com/w/cpp",
        "C++ 核心指南：https://isocpp.github.io/CppCoreGuidelines/",
        "C++ 标准草案（WG21）：https://isocpp.org/std/the-standard",
        "CMake 官方文档：https://cmake.org/documentation/",
        "Compiler Explorer：https://godbolt.org/",
    ],
    [
        "C++ 模板深入，见 026-cpp/062-CppTemplate 文档。",
        "STL 容器与算法，见 026-cpp 模块 STL 文档。",
        "并发与原子，见 026-cpp 模块并发文档。",
        "Rust 内存安全对比，见 053-rust 模块（若已加入）。",
        "尚硅谷 Bilibili 空间（https://space.bilibili.com/302417610 ）提供 C++ 课程。",
    ],
    [
        ("RAII 与所有权设计", [
            "所有权是资源生命周期的归属：栈对象归作用域，unique_ptr 归唯一持有者，shared_ptr 共享所有权，weak_ptr 观察不持有。",
            "传参选择：只读用 const&，需要拷贝用值，转移所有权用 unique_ptr 值传递或 move。",
            "返回选择：返回值（RVO/移动）优先；需要多态返回 unique_ptr<Base>。",
            "容器元素生命周期：容器持有元素值或智能指针；避免裸指针悬垂。",
        ]),
        ("constexpr 与编译期编程", [
            "constexpr 变量与函数在编译期求值，消除运行时开销；consteval（C++20）强制编译期求值。",
            "编译期字符串处理、配置表、哈希可在 constexpr 中实现，配合 static_assert 验证。",
            "模板元编程（如 std::tuple 操作）与 constexpr 互补：前者变换类型，后者计算值。",
            "工程建议：优先 constexpr 函数而非模板递归；编译期逻辑保持可测试（运行时同样可调用）。",
        ]),
    ],
)

KB_LANG["csharp"] = _compact(
    "C#", ".NET、LINQ、异步、泛型",
    [
        "能够说出 C# 的类、属性、泛型、委托与 LINQ 基本语法。",
        "能够解释 .NET 运行时、CLR、GC 与 async/await 模型。",
        "能够编写 .NET 控制台、Web API 与 Unity 脚本。",
        "能够分析内存、并发与 LINQ 延迟执行的原理。",
        "能够评价 C# 与 Java、TypeScript 的异同。",
        "能够设计跨平台 .NET 应用（MAUI/ASP.NET Core）。",
    ],
    [
        "C# 由 Anders Hejlsberg 领导的微软团队于 2000 年发布，随 .NET Framework 1.0 推出，定位是 Windows 平台的主流语言。",
        ".NET Core（2016）把 C# 带到 Linux 与 macOS，.NET 5+ 统一为单一 .NET 平台；当前 LTS 版本 .NET 8（2023）与 .NET 10（2025）。",
        "C# 语言持续现代化：泛型（2.0）、LINQ（3.0）、async/await（5.0）、模式匹配与记录类型（9+）、主构造函数（12）；Unity 游戏引擎使 C# 在游戏开发中占据重要地位。",
    ],
    [
        "CLR 与托管代码：C# 编译为 IL（中间语言），CLR 用 JIT 编译为机器码；GC 管理堆内存，值类型（struct）在栈上或内联。",
        "LINQ：语言集成查询通过扩展方法与表达式树实现，支持延迟执行（IEnumerable）与即时执行（ToList）；表达式树可翻译为 SQL（EF Core）。",
        "async/await：状态机机制把异步方法编译为可挂起的状态机；Task 表示异步操作，ConfigureAwait(false) 控制上下文捕获。",
        "泛型与反射：泛型保留类型信息（与 Java 擦除不同）；反射/源生成器（source generator）用于元编程。",
    ],
    [
        ("LINQ 延迟执行误判", "IEnumerable 查询在枚举时才执行，数据源变化影响结果。需要快照时 ToList。"),
        ("async void", "async void 异常无法被调用方捕获。事件处理器外一律 async Task。"),
        ("阻塞异步调用", ".Result/.Wait() 在 UI 上下文死锁。全程 async/await。"),
        ("可变默认参数", "可选参数默认值必须是编译期常量；引用类型默认 null，注意空引用。"),
        ("字符串拼接", "循环内 += 产生大量垃圾。使用 StringBuilder。"),
        ("Culture 陷阱", "ToString 受区域影响（小数点差异）。使用 InvariantCulture 或格式化说明符。"),
        ("GC 压力", "频繁分配大对象触发 Full GC。使用 ArrayPool、结构体或减少分配。"),
    ],
    [
        "使用可空引用类型（nullable reference types）编译期防空引用。",
        "异步全链路 async/await，禁止 async void。",
        "集合与 LINQ 优先，避免手写循环。",
        "记录类型（record）表达不可变数据。",
        "依赖注入容器管理服务生命周期。",
    ],
    [
        "C# 与 Java：两者都是托管语言；C# 语言特性更新更快，Java 生态更开放。",
        "C# 与 TypeScript：C# 强类型服务端，TypeScript 前端；语法相似，async/await 模型一致。",
        ".NET Framework 与 .NET 8：现代 .NET 跨平台、性能更好，新项目一律 .NET 8+。",
    ],
    [
        "ASP.NET Core：最小 API 或控制器模式；中间件管线；EF Core 数据访问。",
        "解决方案组织：sln + csproj 分项目（Web、Domain、Infrastructure、Tests）。",
        "配置：appsettings.json + 环境变量 + 用户机密（开发）。",
        "测试：xUnit/NUnit + Moq 或纯依赖注入替身。",
    ],
    [
        "需求：实现订单查询 API，支持筛选、分页与统计。",
        "方案：ASP.NET Core Minimal API + EF Core + LINQ。",
        "要点：DTO 隔离实体；IQueryable 组合查询条件；分页参数校验。",
        "验证：集成测试覆盖查询与边界；benchmark 验证大数据量性能。",
    ],
    [
        "C# 的现代性在托管语言中领先：语言特性、工具链与跨平台能力均衡。",
        "异步、LINQ 与泛型是三大支柱，工程代码应熟练运用。",
        "理解 CLR 与 GC 是性能调优的前提。",
    ],
    [
        "Microsoft Learn C# 文档：https://learn.microsoft.com/zh-cn/dotnet/csharp/",
        ".NET 官方文档：https://learn.microsoft.com/zh-cn/dotnet/",
        "ASP.NET Core 文档：https://learn.microsoft.com/zh-cn/aspnet/core/",
        "C# 语言规范：https://learn.microsoft.com/zh-cn/dotnet/csharp/language-reference/",
    ],
    [
        "C# 与 .NET 生态，见 015-csharp 模块基础文档。",
        "异步编程与 Task，见 015-csharp 模块异步文档。",
        "SQL 与 EF Core，见 019-sql 模块。",
        "黑马程序员 Bilibili 空间（https://space.bilibili.com/37974444 ）提供 .NET 课程。",
    ],
    [
        ("async/await 状态机原理", [
            "async 方法被编译器转换为状态机结构：方法开始同步执行到第一个 await，之后挂起；续体在 Task 完成时调度恢复。",
            "SynchronizationContext 决定恢复线程：UI 上下文恢复主线程，ASP.NET Core 默认无上下文（因此无需 ConfigureAwait(false)）。",
            "Task 组合：WhenAll 并行等待，WhenAny 竞速；ValueTask 避免无等待场景的分配。",
            "调试技巧：TaskScheduler.UnobservedTaskException 观察未处理异常；用 AsyncDiagnostics 追踪。",
        ]),
        ("LINQ 与表达式树", [
            "LINQ 两类实现：Enumerable（委托，内存执行）与 Queryable（表达式树，可翻译）。EF Core 把表达式树翻译为 SQL。",
            "延迟执行：Select/Where 不立即执行，foreach/ToList/Count 触发；链式查询组合灵活但注意重复枚举。",
            "表达式树可以动态构建查询条件（组合筛选），是高级查询库的基础。",
            "性能：复杂 LINQ 先用 EF 生成的 SQL 分析，必要时手写 SQL 或投影优化。",
        ]),
    ],
)

KB_LANG["lua"] = _compact(
    "Lua", "table、元表、协程、嵌入式脚本",
    [
        "能够说出 Lua 的变量、函数、table、元表与协程基本语法。",
        "能够解释 table 作为唯一数据结构的设计与元方法机制。",
        "能够编写嵌入主程序（游戏、Nginx、Redis）的脚本。",
        "能够分析 Lua 与 C 交互（Lua C API）与性能特征。",
        "能够评价 Lua 与其他脚本语言在嵌入式场景的取舍。",
        "能够设计基于 Lua 的可扩展配置与脚本系统。",
    ],
    [
        "Lua 由巴西 PUC-Rio 大学的 Roberto Ierusalimschy 等人于 1993 年发布，设计目标是“可嵌入的脚本语言”：解释器小于 300KB，启动快，与 C 无缝集成。",
        "Lua 5.1-5.4 持续演进：5.3 加入整数子类型，5.4 引入 const 变量与关闭值；LuaJIT 是高性能 JIT 实现，广泛用于游戏与性能敏感场景。",
        "Lua 的著名用户：Adobe Lightroom、Redis 脚本、Nginx（OpenResty）、World of Warcraft 插件、Roblox（Luau）与游戏引擎（LÖVE、Defold）。",
    ],
    [
        "table：Lua 唯一的数据结构，同时充当数组、字典、对象与模块；数组索引从 1 开始。",
        "元表（metatable）：通过 __index、__newindex、__add 等元方法改变 table 行为，实现继承与运算符重载。",
        "协程：coroutine.create/resume/yield 实现协作式多任务，适合游戏状态机与生成器。",
        "C API：lua_State 上下文、栈式参数传递，宿主程序可以安全地执行用户脚本。",
    ],
    [
        ("数组索引从 0 开始", "C/JS 习惯导致遍历错误。Lua 数组从 1 开始，# 取长度。"),
        ("# 与 nil 空洞", "表中存在空洞时 # 结果不确定。维护计数或用 pairs 遍历。"),
        ("全局变量污染", "未声明赋值创建全局变量。使用 local 声明，或严格模式（Lua 5.4 _ENV 控制）。"),
        ("元方法误用", "__index 链过长影响性能；循环继承导致死循环。保持元表层级浅。"),
        ("协程栈溢出", "递归协程无终止条件。设计明确的退出路径。"),
        ("字符串拼接性能", "循环内 .. 是 O(n²)。用 table.concat。"),
        ("与 C 交互类型错误", "栈上类型不匹配导致崩溃。检查 lua_type 后再取值。"),
    ],
    [
        "所有变量显式 local 声明。",
        "模块返回 table 并隐藏内部实现。",
        "配置脚本保持纯数据（无副作用）。",
        "宿主调用前校验脚本来源与沙箱环境。",
    ],
    [
        "Lua 与 Python：Python 生态庞大、语法丰富；Lua 轻量、嵌入友好。嵌入式配置与游戏用 Lua。",
        "Lua 5.1 与 5.4：5.4 的整数除法、关闭值、const 是主要差异；注意 LuaJIT 停留在 5.1 语义。",
        "Lua 与 JavaScript：JS 有标准库与引擎生态；Lua 更小更快，适合受限环境。",
    ],
    [
        "Redis 脚本：用 Lua 实现原子操作（EVAL）；OpenResty 用 Lua 编写网关逻辑。",
        "游戏集成：C++ 引擎嵌入 Lua，暴露 API，策划编写逻辑与配置。",
        "测试：busted 框架；性能用 LuaJIT 与 FFI。",
    ],
    [
        "需求：为 Redis 实现原子限流脚本。",
        "方案：Lua 脚本内检查计数、递增、设置过期。",
        "要点：KEYS/ARGV 分离；返回剩余配额；脚本只读操作注意复制。",
        "验证：并发调用验证原子性；过期后配额重置。",
    ],
    [
        "Lua 的定位是嵌入与扩展，小而美是核心优势。",
        "table 与元表是语言的心脏，理解它们才能写出惯用代码。",
        "沙箱与安全是宿主集成的第一优先级。",
    ],
    [
        "Lua 官方文档：https://www.lua.org/docs.html",
        "Lua 5.4 参考手册：https://www.lua.org/manual/5.4/",
        "LuaJIT：https://luajit.org/",
        "OpenResty 文档：https://openresty.org/cn/",
        "Redis EVAL 文档：https://redis.io/docs/latest/develop/programming/",
    ],
    [
        "Lua 与 Redis 脚本，见 022-redis 模块相关文档。",
        "Lua 与 OpenResty 网关，见 031-devops 模块相关文档。",
        "游戏开发与脚本扩展，见 017-lua 模块文档。",
        "黑马程序员 Bilibili 空间（https://space.bilibili.com/37974444 ）提供 Lua 课程。",
    ],
    [
        ("元表与面向对象", [
            "用 table 模拟类：构造函数返回新表，__index 指向类表实现继承；冒号语法 self 绑定。",
            "类继承链：子类 __index 指向父类实例/类表；方法查找沿链上行。",
            "多态与组合：元方法 __call 让 table 可调用；__tostring 控制输出。",
            "工程建议：对象体系保持浅继承，优先组合；性能敏感路径避免动态派发。",
        ]),
        ("Lua C API 集成", [
            "宿主初始化 lua_State，注册 C 函数（lua_pushcfunction），调用 lua_pcall 执行脚本并处理错误。",
            "值传递通过栈：lua_pushnumber/lua_tointeger 等；返回值按栈顺序返回。",
            "用户数据（userdata）包装 C 对象，配合元表实现面向对象接口。",
            "安全：限制可用库（require 白名单）、执行超时（debug.sethook）与内存上限。",
        ]),
    ],
)

KB_LANG["javascript"] = _compact(
    "JavaScript", "原型链、事件循环、闭包、ES 规范",
    [
        "能够说出 JS 的变量、函数、对象、数组与 ES6+ 语法。",
        "能够解释原型链、闭包、事件循环与 this 绑定。",
        "能够编写浏览器交互、Node 服务与工具脚本。",
        "能够分析异步模型、作用域与内存泄漏。",
        "能够评价 JS 与 TypeScript、其他语言的差异。",
        "能够设计现代前端应用（框架 + 工程化）。",
    ],
    [
        "JavaScript 由 Brendan Eich 于 1995 年在 Netscape 用 10 天设计完成，最初只做表单校验；1996 年提交给 ECMA 标准化，即 ECMAScript。",
        "ES6（2015）是语言转折点：let/const、箭头函数、class、Promise、模块化；此后每年发布新版本（ES2016+），现代语法在 Node 与浏览器快速普及。",
        "运行时生态：V8（Chrome/Node）、SpiderMonkey（Firefox）、JavaScriptCore（Safari）；Node.js 与 Deno/Bun 让 JS 成为全栈语言；TypeScript 成为大型项目的事实标准。",
    ],
    [
        "原型链：对象通过 __proto__ 链接原型，属性查找沿链上行；ES6 class 是原型继承的语法糖。",
        "闭包：函数捕获定义时的作用域，变量随函数存活；闭包是模块模式与柯里化的基础。",
        "事件循环：调用栈、任务队列（宏任务）与微任务队列决定执行顺序；Promise 回调进微任务，setTimeout 进宏任务。",
        "this 绑定：默认绑定、隐式绑定、显式绑定（call/apply/bind）与箭头函数词法绑定四种规则。",
    ],
    [
        ("== 隐式转换", "宽松相等产生意外结果。一律使用 ===。"),
        ("var 与提升", "var 函数作用域与提升导致困惑。使用 let/const。"),
        ("回调地狱", "嵌套回调难维护。使用 Promise/async-await。"),
        ("闭包内存泄漏", "闭包引用大对象且长期存活。及时置空引用。"),
        ("浮点精度", "0.1+0.2 != 0.3。金额用整数分或 decimal 库。"),
        ("数组遍历回调 this", "普通函数 this 指向 undefined（严格模式）。用箭头函数。"),
        ("浅拷贝", "Object.assign 浅拷贝嵌套对象仍共享。用 structuredClone 或深拷贝库。"),
        ("setTimeout 精度", "最小 4ms 且受节流影响。动画用 requestAnimationFrame。"),
    ],
    [
        "ESLint + Prettier 统一风格，strict 模式全局开启。",
        "const 优先，let 次之，不使用 var。",
        "异步用 async/await 并处理错误。",
        "模块化（ESM）组织代码，避免全局污染。",
        "类型检查引入 TypeScript（新项目默认）。",
    ],
    [
        "JS 与 TypeScript：TS 是 JS 的超集，增加静态类型；新项目默认 TS。",
        "JS 与 Python：JS 事件驱动适合 I/O 密集前端/服务；Python 生态偏数据与 AI。",
        "CommonJS 与 ESM：Node 传统 CJS（require），现代 ESM（import）；互操作规则需注意。",
    ],
    [
        "前端工程化：Vite 构建、ESLint、Vitest 测试、pnpm 依赖管理。",
        "Node 服务：Express/Fastify 或原生 http；PM2/容器部署。",
        "性能：防抖节流、虚拟列表、代码分割与懒加载。",
        "可观测性：错误上报（window.onerror）、性能指标（web-vitals）。",
    ],
    [
        "需求：实现前端搜索框的防抖与请求竞态处理。",
        "方案：debounce 函数 + AbortController 取消过期请求 + loading 状态。",
        "要点：防抖延迟 300ms；请求序号或 AbortController 保证最新结果。",
        "验证：快速输入模拟，确认只发最终请求且结果一致。",
    ],
    [
        "JS 的单线程事件循环决定了异步编程范式，理解它才能写出无阻塞代码。",
        "原型、闭包、this 是语言基础三件套。",
        "现代工程以 TS + 框架 + 工具链为标准。",
    ],
    [
        "MDN JavaScript 文档：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript",
        "ECMAScript 规范：https://tc39.es/ecma262/",
        "Node.js 官方文档：https://nodejs.org/docs/latest/api/",
        "JavaScript 秘密花园：https://bonsaiden.github.io/JavaScript-Garden/",
        "Can I use：https://caniuse.com/",
    ],
    [
        "JavaScript 基础语法，见 008-javascript 模块文档。",
        "TypeScript 类型系统，见 009-typescript 模块。",
        "浏览器 DOM 与事件，见 006-html5/007-css 模块。",
        "前端框架 React/Vue，见 011-react/010-vue3 模块。",
        "尚硅谷 Bilibili 空间（https://space.bilibili.com/302417610 ）提供 JavaScript 课程。",
    ],
    [
        ("事件循环深入", [
            "宏任务：script、setTimeout、setInterval、I/O、UI 渲染；微任务：Promise.then、queueMicrotask、MutationObserver。",
            "每轮循环：执行一个宏任务，清空整个微任务队列，必要时渲染；微任务中产生的微任务继续执行，可能饿死宏任务。",
            "Node 的事件循环分阶段：timers、pending callbacks、idle、poll、check、close；process.nextTick 优先于微任务。",
            "调试技巧：用 Performance API 测量；async 栈追踪定位未处理拒绝。",
        ]),
        ("this 与作用域", [
            "四种绑定：直接调用（undefined/global）、方法调用（对象）、call/apply/bind（显式）、箭头函数（词法）。",
            "class 方法默认严格模式，事件回调中 this 丢失需绑定或箭头函数。",
            "作用域链：全局 -> 模块 -> 函数 -> 块级（let/const）；闭包保留整个作用域链。",
            "工程建议：避免 this 魔法，优先箭头函数与显式参数。",
        ]),
    ],
)

KB_LANG["typescript"] = _compact(
    "TypeScript", "类型系统、泛型、工具类型、编译配置",
    [
        "能够说出 TS 的类型注解、接口、联合类型、泛型与枚举语法。",
        "能够解释类型系统（结构类型、类型收窄、类型体操）与编译机制。",
        "能够编写类型安全的函数、类与泛型工具。",
        "能够分析类型推断、声明合并与模块解析。",
        "能够评价 TS 与 JS、其他静态语言的设计差异。",
        "能够设计大型项目的类型体系与工程配置。",
    ],
    [
        "TypeScript 由 Anders Hejlsberg 团队于 2012 年发布，定位是 JavaScript 的超集：保留 JS 生态，增加静态类型与编译期检查。",
        "TS 的编译目标覆盖 ES3 到 ES2022+，配合 tsconfig 的严格模式（strict）成为行业标准；2019 年起主流框架（Vue 3、React、Angular）默认 TS。",
        "类型系统持续演进：条件类型、映射类型、模板字面量类型、const 类型参数与 satisfies 操作符；tsc 之外，Vite/ESBuild 用 esbuild 转译加速开发。",
    ],
    [
        "结构类型：TS 的类型兼容基于结构（成员）而非名义；多余属性检查在对象字面量处执行。",
        "类型收窄：typeof、instanceof、in、判别联合与谓词函数（is）让联合类型逐步收窄。",
        "泛型：类型参数 + 约束（extends）实现复用；工具类型（Partial、Pick、Record、ReturnType）基于映射与条件类型。",
        "声明与编译：.ts 编译为 .js；类型声明（.d.ts）描述 JS 库；tsconfig 的 strict、moduleResolution、target 决定行为。",
    ],
    [
        ("any 滥用", "any 使类型检查失效。用 unknown + 收窄，或明确设计类型。"),
        ("非空断言过量", "! 掩盖空值风险。用可选链与显式检查。"),
        ("类型收窄失效", "属性访问后联合类型丢失。用判别联合或保存局部变量。"),
        ("interface 与 type 混用", "两者能力差异（合并、映射）。统一团队规范。"),
        ("枚举数值反推", "数字枚举可被任意数值赋值。优先字符串枚举或 const 对象。"),
        ("tsconfig 宽松", "strict 关闭导致检查形同虚设。新项目 strict: true。"),
        ("import type 混淆", "运行时导入类型导致产物膨胀。使用 import type 或 verbatimModuleSyntax。"),
        ("类型体操过度", "复杂类型影响可读性与编译速度。优先简单类型 + 注释。"),
    ],
    [
        "tsconfig strict 模式 + noUncheckedIndexedAccess。",
        "业务代码类型显式，边界使用 zod 校验运行时数据。",
        "工具类型封装复用，避免重复。",
        "CI 运行 tsc --noEmit 与 ESLint。",
        "第三方库无类型时写最小 .d.ts。",
    ],
    [
        "TS 与 JS：TS 是 JS 超集，新增类型层；迁移渐进可行（allowJs/checkJs）。",
        "TS 与 Java：TS 结构类型灵活，Java 名义类型严格；TS 面向 JS 生态。",
        "tsc 与 esbuild/swc：tsc 全量类型检查；esbuild 快速转译不做类型检查，两者配合使用。",
    ],
    [
        "项目配置：tsconfig 分层（base/app/node）；paths 别名；declaration 输出库类型。",
        "类型安全 API：zod 校验请求体，推断类型（z.infer）。",
        "前端类型共享：monorepo 中 shared 包导出 API 类型，前后端共用。",
        "质量门禁：typecheck、lint、单元测试在 CI 强制。",
    ],
    [
        "需求：为前端请求层实现类型安全封装。",
        "方案：泛型 request 函数 + zod schema 校验 + 错误统一。",
        "要点：响应类型由 schema 推断；网络错误与业务错误区分；取消支持。",
        "验证：类型测试（tsd）与单元测试覆盖。",
    ],
    [
        "TS 的价值是“把错误留在编译期”：类型即文档，重构更安全。",
        "strict 与类型收窄是日常武器，工具类型是进阶工具。",
        "运行时校验（zod）与静态类型互补，边界数据仍要防御。",
    ],
    [
        "TypeScript 官方文档：https://www.typescriptlang.org/docs/",
        "TS 手册中文版：https://www.typescriptlang.org/zh/docs/handbook/",
        "TypeScript 发布计划：https://github.com/microsoft/TypeScript/wiki/Roadmap",
        "tsconfig 参考：https://www.typescriptlang.org/tsconfig/",
        "Type Challenges：https://github.com/type-challenges/type-challenges",
    ],
    [
        "TS 基础类型与接口，见 009-typescript 模块文档。",
        "TS 泛型与工具类型，见 009-typescript 模块进阶文档。",
        "React + TS 组件类型，见 011-react 模块。",
        "Vue3 + TS 组合式 API，见 010-vue3 模块。",
        "尚硅谷 Bilibili 空间（https://space.bilibili.com/302417610 ）提供 TypeScript 课程。",
    ],
    [
        ("条件类型与类型体操", [
            "条件类型 T extends U ? X : Y 在类型层做分支；infer 提取类型片段（ReturnType、Parameters 的底层实现）。",
            "映射类型 { [K in keyof T]: T[K] } 变换对象结构；key remapping（as）过滤键。",
            "模板字面量类型 `${K}Id` 组合字符串类型，配合推断实现精确匹配。",
            "工程建议：类型体操控制在团队可读范围，复杂类型用注释解释意图。",
        ]),
        ("声明文件与模块解析", [
            ".d.ts 声明 JS 库类型：declare module、declare global、export =；@types 包集中管理社区类型。",
            "moduleResolution：node16/nodenext 遵循 ESM/CJS 规则；bundler 模式适配 Vite。",
            "三斜线指令（/// reference）用于旧式依赖声明；现代代码用 import。",
            "发布库时生成 .d.ts 并测试（arethetypeswrong）。",
        ]),
    ],
)
